In [102]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [110]:
import numpy as np
import os
import math

In [103]:
from tensorflow.keras.callbacks import EarlyStopping

In [65]:
image_generator = ImageDataGenerator(rotation_range=25,
                                    width_shift_range=0.2,
                                     height_shift_range=0.2,
                                     shear_range=0.1,
                                     zoom_range=0.2,
                                     horizontal_flip=True,
                                     fill_mode='nearest')

loaded_model = load_model('E:/Faculta/_LICENTA/_Aplicatie/pozeModel2SauModelCuToateBolile/checkPointComplexModel61Accuracy.h5')

In [74]:
image_shape = (300, 300, 1)
batch_size = 1
path_test_imagine = 'E:/Faculta/_LICENTA/_Aplicatie/pozeModel1SauBinaryModel/testeCuTibi'
test_images_generator = image_generator.flow_from_directory(path_test_imagine, target_size=image_shape[:2],
                                                  color_mode='grayscale',
                                                  batch_size=batch_size,
                                                  class_mode='categorical',
                                                  shuffle=False)

Found 34 images belonging to 1 classes.


In [75]:
pred = (loaded_model.predict(test_images_generator))

In [76]:
pred

array([[0.10116115, 0.01608084, 0.01558421, 0.00801023, 0.05102973,
        0.01130821, 0.01064848, 0.00276966, 0.1048798 , 0.01939653,
        0.6034724 , 0.02207821, 0.00881337, 0.00284247, 0.02192467],
       [0.10097066, 0.01601194, 0.01563421, 0.00792647, 0.05097935,
        0.01132913, 0.01051865, 0.0028115 , 0.10347999, 0.01917297,
        0.6054218 , 0.02211504, 0.00883149, 0.00281628, 0.02198052],
       [0.09941134, 0.01603374, 0.01588388, 0.00816018, 0.05117106,
        0.01129431, 0.01048441, 0.00288669, 0.10505661, 0.01934807,
        0.6042428 , 0.02216041, 0.0088064 , 0.00298744, 0.02207272],
       [0.10018503, 0.01521968, 0.01496422, 0.00755739, 0.05014582,
        0.0105584 , 0.01000478, 0.0026042 , 0.10298207, 0.01855554,
        0.6140847 , 0.02119463, 0.00835622, 0.00262926, 0.02095796],
       [0.0984243 , 0.01538336, 0.01519511, 0.00772783, 0.05032037,
        0.01078531, 0.01008991, 0.0026801 , 0.10364202, 0.0187186 ,
        0.61309665, 0.02146631, 0.00839334, 

In [80]:
categoryArray = pred[0]
maximum = np.max(pred[0])
index_of_maximum = np.where(categoryArray == maximum)
index_of_maximum

(array([10], dtype=int64),)

In [83]:
pred[1]

array([0.10097066, 0.01601194, 0.01563421, 0.00792647, 0.05097935,
       0.01132913, 0.01051865, 0.0028115 , 0.10347999, 0.01917297,
       0.6054218 , 0.02211504, 0.00883149, 0.00281628, 0.02198052],
      dtype=float32)

In [92]:
pred[2]*100

array([ 9.9411335 ,  1.6033745 ,  1.588388  ,  0.81601834,  5.117106  ,
        1.1294311 ,  1.0484406 ,  0.2886695 , 10.505661  ,  1.9348072 ,
       60.42428   ,  2.2160408 ,  0.88064027,  0.2987441 ,  2.207272  ],
      dtype=float32)

In [93]:
#####reantreanre model 

In [105]:
train_path = 'E:/Faculta/_LICENTA/_Aplicatie/pozeModel2SauModelCuToateBolile/_trainPics'
test_path = 'E:/Faculta/_LICENTA/_Aplicatie/pozeModel2SauModelCuToateBolile/_testPics'
batch_size = 16
image_shape = (300,300,1)
train_images_model = image_generator.flow_from_directory(train_path,target_size=image_shape[:2],
                                                  color_mode='grayscale',
                                                  batch_size=batch_size,
                                                  class_mode='categorical',
                                                        shuffle=True)
test_images_model = image_generator.flow_from_directory(test_path,target_size=image_shape[:2],
                                                  color_mode='grayscale',
                                                  batch_size=batch_size,
                                                  class_mode='categorical',
                                                  shuffle=False)

Found 58480 images belonging to 15 classes.
Found 9481 images belonging to 15 classes.


In [106]:
from tensorflow.keras.callbacks import ModelCheckpoint

In [107]:
#de schimbat path ul
checkpoint_path = 'E:/Faculta/_LICENTA/_Aplicatie/pozeModel2SauModelCuToateBolile/_checkpoints/checkPointComplexModelImbunatati.h5'
checkpoint_folder = os.path.dirname(checkpoint_path)

In [108]:
checkpoint_call = ModelCheckpoint(checkpoint_path,
                                  save_weighs_only=True,
                                  verbose=1)
early_stop = EarlyStopping(monitor='val_loss',patience=2)

In [111]:
trainedModel = loaded_model.fit(train_images_model,
                                     steps_per_epoch=int(math.ceil(train_images_model.n/batch_size)),
                                     epochs=10,
                                     validation_data= test_images_model,
                                     callbacks = [early_stop,checkpoint_call],
                                     verbose=1)

Epoch 1/10
 189/3655 [>.............................] - ETA: 3:36:53 - loss: 1.7449 - accuracy: 0.5298

KeyboardInterrupt: 